App\Entity\systemTemplate:
  attributes:
    name:
      groups: [ systemTemplate_read, systemTemplate_create, systemTemplate_update ]
    json:
      groups: [ systemTemplate_read, systemTemplate_create, systemTemplate_update ]
    header:
      groups: [ systemTemplate_read, systemTemplate_create, systemTemplate_update ]
    body:
      groups: [ systemTemplate_read, systemTemplate_create, systemTemplate_update ]
    footer:
      groups: [ systemTemplate_read, systemTemplate_create, systemTemplate_update ]
    idSystemOrientation:
      groups: [ systemTemplate_read, systemTemplate_create, systemTemplate_update ]
    idSystemSize:
      groups: [ systemTemplate_read, systemTemplate_create, systemTemplate_update ]
    headerSpacing:
      groups: [ systemTemplate_read, systemTemplate_create, systemTemplate_update ]
    footerSpacing:
      groups: [ systemTemplate_read, systemTemplate_create, systemTemplate_update ]
    idSystemFrontPage:
      groups: [ systemTemplate_read, systemTemplate_create, systemTemplate_update ]
    marginLeft:
      groups: [ systemTemplate_read, systemTemplate_create, systemTemplate_update ]
    marginRight:
      groups: [ systemTemplate_read, systemTemplate_create, systemTemplate_update ]
    marginTop:
      groups: [ systemTemplate_read, systemTemplate_create, systemTemplate_update ]
    marginBottom:
      groups: [ systemTemplate_read, systemTemplate_create, systemTemplate_update ]
    script:
      groups: [ systemTemplate_read, systemTemplate_create, systemTemplate_update ]
    paginate:
      groups: [ systemTemplate_read, systemTemplate_create, systemTemplate_update ]